### ISSUE TITLE
Не подгружается контроллер

### ISSUE THREAD

**Issue by Sadykh** [Nafania/yii-based-torrent-tracker#1]
На хостинге вываливается ошибка:
Fatal error: Class 'components\Controller' not found ../protected/controllers/SiteController.php on line 3

Версия PHP — 5.4.9-4ubuntu2.3

Права 0755, владелец папок указан верно.

**Comment by Nafania** [comment]
У вас точно все файлы на месте? Конфиг отредактирован правильно, под ваши настройки?

**Comment by Sadykh** [comment]
Да, все файлы на месте.
Конфиг я взял из папки /local/, перенёс в production, указал данные БД. Переменную $yii из конфига убрал и внёс в index.php. 

UPD: ещё хочу добавить, что я пытался установить ветку dev, а не master.

**Comment by Nafania** [comment]
А зачем вы переносили переменную $yii?
