### ISSUE TITLE
Недоступность сайта после установки

### ISSUE THREAD

**Issue by ghost** [Nafania/yii-based-torrent-tracker#2]
После настройки и загрузки файлов на сервер, сайт становится недоступным.
Ощущение будто бы неправильные пути где-то прописаны, либо отсутствуют какие-то файлы.
Производил изменения:
в корневую сайта добавлен фреймворк

в файлы:
/protected/config/production/config.php
/protected/config/production/console.php
внесены данные:
        'db' => array(
            'connectionString' => 'mysql:host=localhost;dbname=torrent_db',
            'username' => 'torrent',
            'password' => 'djF75f22i4rS3J5F',
            'schemaCachingDuration' => 3600,
            'enableParamLogging' => false,
            'enableProfiling' => false,
            'charset' => 'utf8',
            'tablePrefix' => '',
        ),

здесь же прописан полный путь к фреймворку:
$yii = '/var/www/vhosts/torrent/htdocs/yii-1.1.15.022a51/framework/yii.php';

В базу данных залит дамп из файла:
/protected/migrations/initialSetup.sql

Уверен, что произвел неполную настройку. Опыт работы с Yii отсутствует.
Интересуют пропущенные этапы установки.

**Comment by Nafania** [comment]
@loginick Залейте дамп из папки data.
Далее, используйте конфиги в production с суффиксом example для конфигурации, убрав из них -example.
Если вы получаете белый экран, то значит произошла критическая ошибка, смотрите в логе ошибок php или веб-сервера.

**Comment by ghost** [comment]
Да, действительно,
PHP Parse error:  syntax error, unexpected '[' in /var/www/vhosts/torrent/htdocs/protected/config/production/config.php on line 24
Причина в версии PHP. Установлен PHP 5.3.3

**Comment by Nafania** [comment]
@loginick в проекте частично используется короткий синтаксис задания массивов, поэтому версия пхп должна быть не ниже, чем 5.4

**Comment by ghost** [comment]
Обновился до 5.4. К сожалению, следующая ошибка

PHP Fatal error:  Class 'components\Controller' not found in /var/www/vhosts/torrent/htdocs/protected/controllers/SiteController.php on line 4

**Comment by Nafania** [comment]
@RLLC у вас все файлы на месте?

**Comment by ghost** [comment]
Да, конечно. Классы присутствуют. Подозреваю, что требуется дополнительная конфигурация сервера.

**Comment by Nafania** [comment]
@lpko конфиги скопированы с приложенных -example? Потому что за импорт данного файла отвечает вот эта строка https://github.com/Nafania/yii-based-torrent-tracker/blob/dev/dev/protected/config/production/config-example.php#L16

**Comment by ghost** [comment]
Да, предварительно убрав -example. Я могу отправить вам данные от ftp на почту?

**Comment by Nafania** [comment]
А смысл мне в данных от фтп? Какая у вас ОСь? Какая точно версия пхп?

**Comment by ghost** [comment]
CentOS release 6.5 / PHP Version 5.4.31 / Server API Apache 2.0 Handler
какие рекомендации по настройке, скорее дело в конфигурации?

**Comment by Nafania** [comment]
Да нет, особой конфигурации не требуется. Киньте данные от фтп в ЛС на форуме Yii http://yiiframework.ru/forum/memberlist.php?mode=viewprofile&u=1610

**Comment by ghost** [comment]
данные отправил

**Comment by Nafania** [comment]
У вас какие-то странные права на папки и файлы стоят, я подозреваю, что проблема в этом.
Посмотрите вот эти ссылки:
http://www.yiiframework.com/wiki/275/how-to-write-secure-yii-applications/#hh16
http://www.yiiframework.com/forum/index.php/topic/27649-framework-folder-permissions/
http://www.yiiframework.com/forum/index.php/topic/22133-change-permission-of-directories-deployment-yii/page__view__findpost__p__108356

**Comment by ghost** [comment]
Можно получить работающий пример на одном из хостингов с поддержкой apc, и полный архив с настройками с этого хостинга?
Установил Apache MPM-ITK, запуск файлов от имени владельца не помог.
Загружен был архив с файлами, а не каждый файл отдельно через FTP, и это не помогло.
Ошибка Class 'components\Controller' not found сохраняется.
Права с статей выше были соблюдены.

**Comment by Nafania** [comment]
Нда, странное дело. Вы пробовали вместо апача использовать nginx + php-fpm?

**Comment by ghost** [comment]
Нет. Мне известно, что nginx лучше использовать как проксирующий сервер. Сейчас нет такой необходимости.
Я устанавливал сторонюю систему yupe.ru, она на Yii и работает корректно.

**Comment by ghost** [comment]
Как мне быть?

**Comment by Nafania** [comment]
Скажите, пожалуйста, полную конфигурацию сервера:
ОСь
Веб-сервер (тип, версия, как подключен пхп)
Пхп
Редис
База данных

**Comment by ghost** [comment]
OS - CentOS release 6.5 (Final)
Server - Apache MPM-ITK с репозитория Epel, версия 2.2.22, php обычно
PHP - PHP 5.4.32 (cli)
Redis - на сервер не устанавливал
БД - MySQL 5.5.39

хорошо бы инсталлятор, который бы проверил систему и помог установить.

**Comment by Nafania** [comment]
У фреймворка есть папка requirements, проверяет настройки сервера.
Редис нужен для работы, вам придется его поставить, иначе не взлетит.
Еще желателен сфинкс для поиска, но не обязателен.

**Comment by ghost** [comment]
Пожалуйста, дайте рекомендации по настройке редиса и сфинкса либо ссылки на статьи.

**Comment by Nafania** [comment]
Редис достаточно просто установить. Для сфинкса добавлю конфиг в репозитарий позже.

**Comment by ghost** [comment]
Так, ну с сервером проблем нет. Он установился одной командой. Проблемы с PhpRedis.
Юзал эту статью http://exploradium.net/ru/blog/kak-ustanovit-redis-i-redis-php-klient.html
По команде yum install php5-dev в репозиториях пусто. Измотал меня этот Yii, но мне нужен этот скрипт ибо я видел его в действии.

**Comment by Nafania** [comment]
У вас же centos, ставьте все из пакетов. yum install php-redis
